# %% [markdown]
# # Exponential Function
#
# In this notebook, we review some properties of the complex exponential function.
# This function plays an important role for defining and understanding the Fourier
# transform.

# %% [markdown]
# ## Power Series
#
# The real exponential function exp: R -> R can be characterized by the limit definition:
# exp(a) = lim_{n->inf} (1 + a/n)^n
#
# The constant e := exp(1) ~ 2.71828 is known as Euler's number.
#
# The exponential function can also be expressed by the power series:
# exp(a) := sum_{n=0}^{inf} a^n / n!
#
# Replacing the real-valued variable a by a complex-valued variable c, one obtains
# the complex exponential function exp: C -> C

# %%
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline


def exp_power_series(c, N):
    """Compute power series for exponential function

    Args:
        c: Complex number
        N: Number of summands used for approximation

    Returns:
        exp_c: Approximation of exp(c)
    """
    exp_c = 1
    c_power = 1
    nfac = 1
    for n in range(1, N):
        nfac *= n
        c_power *= c
        exp_c += c_power / nfac
    return exp_c


c = 1
print('Approximation (N =  1):', exp_power_series(c, 1))
print('Approximation (N =  2):', exp_power_series(c, 2))
print('Approximation (N =  4):', exp_power_series(c, 4))
print('Approximation (N =  8):', exp_power_series(c, 8))
print('Approximation (N = 12):', exp_power_series(c, 12))
print('Numpy:                 ', np.exp(c))

# %% [markdown]
# ## Exponentiation Identity and Euler's Formula
#
# The **exponentiation identity** states that:
# exp(c1 + c2) = exp(c1) * exp(c2)
#
# **Euler's formula** relates the values of the exponential function at purely
# imaginary arguments to trigonometric functions:
# exp(i*gamma) = cos(gamma) + i*sin(gamma)
#
# This explains the periodic behavior along the imaginary axis.

# %%
A, B = np.meshgrid(np.arange(-2, 2, 0.1), np.arange(-12, 12, 0.1))
C = A + B * 1j
f_exp = np.exp(C)

plt.figure(figsize=(12, 4))
extent = [-2, 2, -12, 12]

plt.subplot(1, 3, 1)
plt.imshow(np.real(f_exp), aspect='auto', cmap='seismic', origin='lower', extent=extent)
plt.title('Real part Re(exp(c))')
plt.xlabel('a = Re(c)')
plt.ylabel('b = Im(c)')
plt.colorbar()

plt.subplot(1, 3, 2)
plt.imshow(np.imag(f_exp), aspect='auto', cmap='seismic', origin='lower', extent=extent)
plt.title('Imaginary part Im(exp(c))')
plt.xlabel('a = Re(c)')
plt.ylabel('b = Im(c)')
plt.colorbar()

plt.subplot(1, 3, 3)
plt.imshow(np.abs(f_exp), aspect='auto', cmap='gray_r', origin='lower', extent=extent)
plt.title('Absolute value |exp(c)|')
plt.xlabel('a = Re(c)')
plt.ylabel('b = Im(c)')
plt.colorbar()

plt.tight_layout()
plt.show()

# %% [markdown]
# ## Basic Properties
#
# The exponential function has a number of interesting properties:
# - exp(i*gamma) = exp(i*(gamma + 2*pi))  [periodicity]
# - |exp(i*gamma)| = 1  [unit circle]
# - conj(exp(i*gamma)) = exp(-i*gamma)
# - exp(i*(gamma1 + gamma2)) = exp(i*gamma1) * exp(i*gamma2)
# - d(exp(i*gamma))/d(gamma) = i*exp(i*gamma)

# %%
from matplotlib import ticker

# Use colormaps directly instead of get_cmap (works with newer matplotlib)
cmap = plt.colormaps['hsv']  # hsv is nice because it is a circular color map

N = 64

fig = plt.figure(figsize=(5 * 3, 5))
ax1 = fig.add_subplot(1, 3, 1, projection='polar')
ax2 = fig.add_subplot(1, 3, 2)
ax3 = fig.add_subplot(1, 3, 3)

for i in range(N):
    gamma = 2 * np.pi * i / N
    c = np.exp(1j * gamma)
    color = cmap(i / N)
    ax1.plot([0, np.angle(c)], [0, np.abs(c)], color=color)
    ax1.plot(np.angle(c), np.abs(c), 'o', color=color)
    ax2.plot(gamma, np.real(c), 'o', color=color)
    ax3.plot(gamma, np.imag(c), 'o', color=color)

ax2.grid()
ax2.set_xlabel('$\gamma$ [radians]')
ax2.set_ylabel(r'$\mathrm{Re}(\exp(i \gamma))$')
ax2.xaxis.set_major_formatter(ticker.FormatStrFormatter('$%s$'))

ax3.grid()
ax3.set_xlabel('$\gamma$ [radians]')
ax3.set_ylabel(r'$\mathrm{Im}(\exp(i \gamma))$')
ax3.xaxis.set_major_formatter(ticker.FormatStrFormatter('$%s$'))

plt.tight_layout()
plt.show()

# %% [markdown]
# ## Roots of Unity
#
# Let N > 0 be a positive integer. A complex number rho is called an Nth **root of unity**
# if rho^N = 1. There are exactly N distinct Nth roots of unity.
#
# If rho^n != 1 for all n in [1:N-1], it is called a **primitive** Nth root of unity.
# rho_N := exp(2*pi*i/N) is such a primitive Nth root of unity.
#
# All Nth roots of unity can be generated by considering powers of rho_N:
# 1 = rho_N^0, rho_N^1, rho_N^2, ..., rho_N^(N-1)

# %%
from math import gcd
import sys
sys.path.append('..')
import libfmp.c2


def plot_root_unity(N, figsize=(5, 5)):
    root_unity = np.exp(2j * np.pi / N)
    root_unity_power = 1

    fig, ax = plt.subplots(figsize=figsize)
    plt.grid()
    plt.xlim([-1.4, 1.4])
    plt.ylim([-1.4, 1.4])
    plt.xlabel('$\mathrm{Re}$')
    plt.ylabel('$\mathrm{Im}$')
    plt.title('Roots of unity for $N=%d$' % N)

    for n in range(0, N):
        colorPlot = 'r' if gcd(n, N) == 1 else 'k'
        libfmp.c2.plot_vector(root_unity_power, color=colorPlot)
        plt.text(np.real(1.2 * root_unity_power), np.imag(1.2 * root_unity_power),
                 r'$\rho_{%s}^{%s}$' % (N, n), size='18',
                 color=colorPlot, ha='center', va='center')
        root_unity_power *= root_unity

    circle_unit = plt.Circle((0, 0), 1, color='lightgray', fill=0)
    ax.add_artist(circle_unit)
    plt.show()


plot_root_unity(N=8)
plot_root_unity(N=11)
plot_root_unity(N=12)

# %% [markdown]
# ---
# **Acknowledgment:** This notebook was created by Meinard Muller and Frank Zalkow.
