# %% [markdown]
# # Waves and Waveforms
#
# Following Section 1.3.1 of [Muller, FMP, Springer 2015], we introduce the
# concept of waveforms and their visualization.

# %% [markdown]
# ## Pressure-Time Plot
#
# A **sound** is generated by a vibrating object (vocal cords, string, drum).
# These vibrations cause displacements of air molecules, resulting in regions
# of compression and rarefaction. The alternating pressure travels through the
# air as a **wave**.
#
# The change in air pressure at a location can be represented by a
# **pressure-time plot** or **waveform** - showing deviation from average
# air pressure.

# %% [markdown]
# ## Waveform of Sinusoid
#
# If high and low pressure points repeat in an alternating, regular fashion,
# the waveform is **periodic**. The **period** is the time to complete one cycle.
# The **frequency** (in Hertz) is the reciprocal of the period.
#
# A **sinusoid** is the simplest periodic waveform, specified by:
# - Frequency
# - Amplitude (peak deviation from mean)
# - Phase (position in cycle at time zero)

# %%
import os
import numpy as np
from matplotlib import pyplot as plt
import librosa

%matplotlib inline

# %%
# Generate and plot a sinusoid
Fs = 100
duration = 2
amplitude = 1.5
phase = 0.1
frequency = 3

num_samples = int(Fs * duration)
t = np.arange(num_samples) / Fs
x = amplitude * np.sin(2 * np.pi * (frequency * t - phase))

plt.figure(figsize=(10, 2))
plt.plot(t, x, color='blue', linewidth=2.0, linestyle='-')
plt.xlim([0, duration])
plt.xlabel('Time (seconds)')
plt.ylabel('Amplitude')
plt.title(f'Sinusoid: {frequency} Hz')
plt.tight_layout()
plt.show()

# %% [markdown]
# ## Waveform of Real Audio Example
#
# A piano recording of a C major scale demonstrates a real-world waveform.

# %%
# Load and plot audio waveform
Fs = 11025
x, Fs = librosa.load(os.path.join('..', 'data', 'C1', 'FMP_C1_Scale-Cmajor_Piano.wav'), sr=Fs)
t = np.arange(x.shape[0]) / Fs

plt.figure(figsize=(10, 2))
plt.plot(t, x, color='gray')
plt.xlabel('Time (seconds)')
plt.ylabel('Amplitude')
plt.xlim([t[0], t[-1]])
plt.ylim([-0.51, 0.51])
plt.title('C Major Scale - Piano')
plt.tick_params(direction='in')
plt.tight_layout()
plt.show()

# %% [markdown]
# ## Zooming into the Waveform
#
# Zooming into a 50-ms section, we can count about 13 high-pressure points,
# corresponding to approximately 260 Hz - the fundamental frequency of C4.

# %%
# Zoom into a section of the waveform
time_start = 0.66
time_end = 0.71
index_start = int(np.round(Fs * time_start))
index_end = int(np.round(Fs * time_end))
x_crop = x[index_start:index_end]
t_crop = t[index_start:index_end]

plt.figure(figsize=(10, 2))
plt.plot(t_crop, x_crop, color='gray')
plt.xlabel('Time (seconds)')
plt.ylabel('Amplitude')
plt.xlim([t_crop[0], t_crop[-1]])
plt.ylim([-0.51, 0.51])
plt.title('Zoomed waveform showing ~13 cycles in 50ms = ~260 Hz (C4)')
plt.tick_params(direction='in')
plt.tight_layout()
plt.show()

# %% [markdown]
# ## Wave Propagation
#
# A mechanical **wave** is an oscillation that travels through space, transferring
# energy. Types of waves:
#
# - **Transverse wave**: Oscillation perpendicular to propagation direction
#   (e.g., vibration in a string)
# - **Longitudinal wave**: Oscillation parallel to propagation direction
#   (e.g., sound waves)
# - **Combined wave**: Both motions (e.g., water waves with circular motion)

# %%
import matplotlib.animation as animation


def create_grid_pos(x_size=5, y_size=5):
    """Create grid positions for wave visualization"""
    x_pos = np.zeros((y_size, x_size))
    y_pos = np.zeros((y_size, x_size))
    for x in range(x_size):
        y_pos[:, x] = np.arange(y_size)
    for y in range(y_size):
        x_pos[y, :] = np.arange(x_size)
    return x_pos, y_pos


def transverse_wave(x_positions, y_positions, frames_per_cycle=20, wave_len=10,
                    amplitude=1, phase=0, num_frames=100):
    """Generate transverse wave animation frames"""
    k = 2 * np.pi / wave_len
    omega = 2 * np.pi / frames_per_cycle
    x_frames = np.zeros((num_frames, x_positions.shape[0], x_positions.shape[1]))
    y_frames = np.zeros((num_frames, y_positions.shape[0], y_positions.shape[1]))

    for t in range(num_frames):
        x_frames[t, :, :] = x_positions
        for x in range(x_positions.shape[1]):
            y_frames[t, :, x] = y_positions[:, x] + amplitude * np.sin(
                k * x_positions[:, x] - omega * t + phase)
    return x_frames, y_frames


def longitudinal_wave(x_positions, y_positions, frames_per_cycle=20, wave_len=10,
                      amplitude=1, phase=0, num_frames=100):
    """Generate longitudinal wave animation frames"""
    k = 2 * np.pi / wave_len
    omega = 2 * np.pi / frames_per_cycle
    x_frames = np.zeros((num_frames, x_positions.shape[0], x_positions.shape[1]))
    y_frames = np.zeros((num_frames, y_positions.shape[0], y_positions.shape[1]))

    for t in range(num_frames):
        y_frames[t, :, :] = y_positions
        for x in range(x_positions.shape[1]):
            x_frames[t, :, x] = x_positions[:, x] + amplitude * np.sin(
                k * x_positions[:, x] - omega * t + phase)
    return x_frames, y_frames


# %%
# Create wave visualization (static frame)
x_size = 20
y_size = 5
x_pos, y_pos = create_grid_pos(x_size=x_size, y_size=y_size)

# Generate single frame of transverse wave
x_trans, y_trans = transverse_wave(x_pos, y_pos, frames_per_cycle=100,
                                   wave_len=10, amplitude=1, num_frames=1)

fig, ax = plt.subplots(figsize=(8, 3))
ax.scatter(x_trans[0, :, :], y_trans[0, :, :])
ax.set_xlim([-1.5, x_size + 0.5])
ax.set_ylim([-1.5, y_size + 0.5])
ax.set_title('Transverse Wave (single frame)')
ax.axis('off')
plt.tight_layout()
plt.show()

# %% [markdown]
# ---
# **Acknowledgment:** This notebook was created by Meinard Muller and Tim Zunner.
